protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		$this->render('index');
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
	    if($error=Yii::app()->errorHandler->error)
	    {
	    	if(Yii::app()->request->isAjaxRequest)
	    		echo $error['message'];
	    	else
	        	$this->render('error', $error);
	    }
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$headers="From: {$model->email}\r\nReply-To: {$model->email}";
				mail(Yii::app()->params['adminEmail'],$model->subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}


	public function actionPanel()
	{
		if(Yii::app()->user->isGuest)
		{

			$this->redirect(Yii::app()->homeUrl);

		}
		else
		{
			$this->render('panel');
		}
	}
	public function actionRegistro ()
	{
		$model = new ValidarRegistro;
		
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

	

		$this->render('registro', array('model' => $model));
	}
}

protected/controllers/TsuspendidosController.php
<?php

class TsuspendidosController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin','jcarrillo'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Tsuspendidos;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Tsuspendidos']))
		{
			$model->attributes=$_POST['Tsuspendidos'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id_suspendido));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Tsuspendidos']))
		{
			$model->attributes=$_POST['Tsuspendidos'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id_suspendido));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Tsuspendidos');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Tsuspendidos('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Tsuspendidos']))
			$model->attributes=$_GET['Tsuspendidos'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Tsuspendidos::model()->findByPk((int)$id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='tsuspendidos-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/TusuarioController.php
<?php

class TusuarioController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	/*public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('*'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin','jcarrillo'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
*/
	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Tusuario;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Tusuario']))
		{
			$model->attributes=$_POST['Tusuario'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id_usuario));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Tusuario']))
		{
			$model->attributes=$_POST['Tusuario'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id_usuario));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Tusuario');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Tusuario('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Tusuario']))
			$model->attributes=$_GET['Tusuario'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Tusuario::model()->findByPk((int)$id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='tusuario-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	
}

protected/views/layouts/column1.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php $this->beginContent('//layouts/main'); ?>
<div>
	<div class="span-19">
		<div id="content">
			<?php echo $content; ?>
		</div><!-- content -->
	</div>
	<div class="span-5 last">
		<div id="sidebar">
		<?php
			$this->beginWidget('zii.widgets.CPortlet', array(
				'title'=>'Operations',
			));
			$this->widget('zii.widgets.CMenu', array(
				'items'=>$this->menu,
				'htmlOptions'=>array('class'=>'operations'),
			));
			$this->endWidget();
		?>
		</div><!-- sidebar -->
	</div>
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<html lang="en">
<!-- Mirrored from themes.startbootstrap.com/flex-admin-v1.2/ by HTTrack Website Copier/3.x [XR&CO'2008], Tue, 17 Feb 2015 16:05:39 GMT -->
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" name="viewport">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Cambio Modalidad</title>
    <!-- PACE LOAD BAR PLUGIN - This creates the subtle load bar effect at the top of the page. -->
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/public/css/plugins/css_pace/pace.css" rel="stylesheet" />
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/public/css/demo.css" rel="stylesheet" />
    <script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/plugins/css_pace/pace.js"></script>
	
    <!-- GLOBAL STYLES - Include these on every page. -->
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/public/css/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/public/fonts.googleapis.com/css3ef8.css?family=Ubuntu:300,400,500,700,300italic,400italic,500italic,700italic" rel="stylesheet" type="text/css">
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/public/fonts.googleapis.com/css5c84.css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/public/icons/font-awesome/css/font-awesome.min.css" rel="stylesheet" />

    <!-- PAGE LEVEL PLUGIN STYLES -->
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/public/css/plugins/messenger/messenger.css" rel="stylesheet" />
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/public/css/plugins/messenger/messenger-theme-flat.css" rel="stylesheet" />
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/public/css/plugins/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" />
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/public/css/plugins/morris/morris.css" rel="stylesheet" />
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/public/css/plugins/jvectormap/jquery-jvectormap-1.2.2.css" rel="stylesheet" />
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/public/css/plugins/datatables/datatables.css" rel="stylesheet" />
    <!-- THEME STYLES - Include these on every page. -->
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/public/css/style.css" rel="stylesheet" />
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/public/css/plugins.css" rel="stylesheet" />

    <!-- THEME DEMO STYLES - Use these styles for reference if needed. Otherwise they can be deleted. -->
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/public/css/demo.css" rel="stylesheet" />

    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<!-- GLOBAL SCRIPTS -->
    <script src="<?php echo Yii::app()->request->baseUrl;?>/public/ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/plugins/bootstrap/bootstrap.min.js"></script>
    <script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/plugins/popupoverlay/jquery.popupoverlay.js"></script>
    <script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/plugins/popupoverlay/defaults.js"></script>
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css"/>
	<script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
    <script src="<?php echo Yii::app()->request->baseUrl;?>/assets/31fa6451/gridview/jquery.yiigridview.js"></script>
    <script src="<?php echo Yii::app()->request->baseUrl;?>/assets/31fa6451/listview/jquery.yiilistview.js"></script>
    <!-- Logout Notification jQuery -->
    <script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/plugins/popupoverlay/logout.js" type="text/javascript"></script>
    <!-- HISRC Retina Images -->
    <script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/plugins/hisrc/hisrc.js" type="text/javascript"></script>

    <!-- PAGE LEVEL PLUGIN SCRIPTS -->
    <!-- HubSpot Messenger -->
    <script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/plugins/messenger/messenger.min.js" type="text/javascript"></script>
    <script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/plugins/messenger/messenger-theme-flat.js" type="text/javascript"></script>
    <!-- Date Range Picker -->
    <script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/plugins/daterangepicker/moment.js" type="text/javascript"></script>
    <script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
    <!-- Morris Charts -->
    <script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/plugins/morris/raphael-2.1.0.min.js" type="text/javascript"></script>
    <!-- Flot Charts -->
    <script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/plugins/flot/jquery.flot.js" type="text/javascript"></script>
    <script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/plugins/flot/jquery.flot.resize.js" type="text/javascript"></script>
    <!-- Sparkline Charts -->
    <script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
    <!-- Moment.js -->
    <script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/plugins/moment/moment.min.js" type="text/javascript"></script>
    <!-- jQuery Vector Map -->
    <script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
    <script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/plugins/jvectormap/maps/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
    <script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/demo/map-demo-data.js"></script>
    <!-- Easy Pie Chart -->
    <script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/plugins/easypiechart/jquery.easypiechart.min.js" type="text/javascript"></script>
    <!-- DataTables -->    <!-- THEME SCRIPTS -->
<script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/flex.js" type="text/javascript"></script>
<script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/angular/angular.min.js"></script> 
<script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/angular/controller/usuario.js"></script> 
<script src="<?php echo Yii::app()->request->baseUrl;?>/public/js/angular/app/aplicacion.js"></script> 

<!-- Logout Notification Box -->
           <div id="logout">
        <div class="logout-message">
            
                <i class="fa fa-sign-out text-blue"></i> Desea salir?
            </h3>
            <p>Seleccione "Cerrar sesión"<br> para terminar la sesion actual.</p>
            <ul class="list-inline">
                <li>
                    <a href="<?php echo Yii::app()->request->baseUrl;?>/site/login" class="btn btn-blue">
                        <strong>Cerrar sesion</strong>
                    </a>
                </li>
                <li>
                    <button class="logout_close btn btn-blue">Cancelar</button>
                </li>
            </ul>
        </div>
    </div>
    <!-- /#logout -->
    
<?php echo $content;?>
</body>
</html>

protected/views/layouts/mainoriginal.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />
	
	<link href="<?php echo Yii::app()->request->baseUrl; ?>/public/boostrap/css/bootstrap.css" rel="stylesheet" />
	<link href="<?php echo Yii::app()->request->baseUrl; ?>/public/boostrap/css/bootstrap.min.css" rel="stylesheet" />
	
	<H2><title><?php echo CHtml::encode($this->pageTitle); ?></title></H2>	
</head>

<body>

	<div class="container" id="page">

		<div id="header">
			<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
		</div><!-- header -->
				
				<div id="mainmenu">
					<?php $this->widget('zii.widgets.CMenu',array('items'=>array(
					array('label'=>'Inicio','icon'=>'home','url'=>array('/site/index')),
					/*array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
					array('label'=>'Contact', 'url'=>array('/site/contact')),*/
					array('label'=>'Suspender', 'url'=>array('/tdatosPersonal/create')),
                    /*array('label'=>'Datos Suspension', 'url'=>array('/tsuspendidos/admin')),*/
					/*array('label'=>'Registrarse', 'url'=>array('/tusuario/create'), 'visible'=>Yii::app()->user->isGuest),*/
					array('label'=>'Iniciar sesión', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
					/*array('label'=>'Panel de control ('.Yii::app()->user->name.')', 'url'=>array('/site/panel'), 'visible'=>!Yii::app()->user->isGuest),*/
					array('label'=>'Cerrar sesión ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
					),
					'htmlOptions'=> array('class' => 'nav navbar-nav'),
					)); ?>
				</div><!-- mainmenu -->
		


	
	<div class="container">
		<div class="page-header">
			<br /><br />
			<?php if(isset($this->breadcrumbs)):?>
			<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
			)); ?><!-- breadcrumbs -->
	
			<?php endif?>
		</div>

			<?php echo $content; ?>
	</div>
</div><!-- page -->
</body>
</html>
<script src="<?php echo Yii::app()->request->baseUrl; ?>/public/js/jquery.js"></script>


<script src="<?php echo Yii::app()->request->baseUrl; ?>/public/js/jquery-ui-1.10.3.full.min.js"></script>